apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: mysql-svc
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
      name: http
  clusterIP: None
  selector:
    app: mysql-pod

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-ss
  labels:
    name: mysql-ss
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mysql
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "mysql"
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-volumes
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-volumes
          persistentVolumeClaim:
            claimName: mysql-pvc