apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  labels:
    name: redis-svc
spec:
  type: NodePort
  ports:
    - port: 6379
      nodePort: 30003
  selector:
    app: redis-pod

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-rc
  labels:
    name: redis-rc
spec:
  replicas: 1
  selector:
    app: redis-pod
  template:
    metadata:
      labels:
        app: redis-pod
    spec:
      containers:
        - name: redis
          image: redis
          resources:
            requests:
              cpu: 100m              #限制cpu的数量为0.1个
              memory: 100Mi      #限制内存为100M
          ports:
            - containerPort: 6379
