apiVersion: v1
kind: Service
metadata:
  name: spring-svc
  namespace: default
  labels:
    app: spring-svc
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30002
  selector:
    app: spring-pod

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
  labels:
    app: spring-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-pod
  template:
    metadata:
      labels:
        app: spring-pod
    spec:
      containers:
        - name: springdemo
          image: vlaser/springdemo
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /
              scheme: HTTP
            periodSeconds: 15
            initialDelaySeconds: 30
